baseURL: https://amostay.xyz/
languageCode: en-us
title: amos tay
theme: "PaperMod"

params:
  
  defaultTheme: light
  
  homeInfoParams:
          Title: "Hello 👋 "
          Content: >
              I'm **Amos** and this is my personal site.
              
              - Here I (plan to) write about personal thoughts and experiences, and learnings from a career in Data Analytics.
              
              - All opinions are my own.
              
  socialIcons:
      - name: github
        url: "https://github.com/carbanzo"
      - name: LinkedIn
        url: "https://www.linkedin.com/in/amos-tay-785582a3/"
      - name: RsS
        url: "index.xml"
